<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application folder not writable!' => '',
    'Application folder: {folder}' => '',
    'Installed PHP version not support!' => '',
    'Please update installed modules when new version is available!' => '',
    'Switch to default theme after update (strongly recommended)' => '',
    'The currently installed PHP version is too old. Please update before proceed.' => '',
    'The updater requires write access to <strong>all</strong> files and folders in the application root folder.' => '',
    '<strong>Update</strong> HumHub' => 'HumHub <strong>Güncelleme</strong>',
    '<strong>Update</strong> to HumHub {version}' => 'HumHub <strong>{version}</strong> güncelleme',
    'Abort' => 'İptal et',
    'Backup all your files & database before proceed' => 'Tüm dosyalarınızı ve veritabanını yedekleyin',
    'Changes to HumHub core files may overwritten during update!' => 'Güncelleme sırasında HumHub çekirdek dosyalarındaki değişiklikler üzerine yazılabilir!',
    'Cleanup update files' => 'Güncelleme dosyalarını temizle',
    'Close' => 'Kapat',
    'Could not extract update package!' => 'Güncelleştirme paketi açılamadı!',
    'Could not get update info online! (%error%)' => 'Aktif güncelleme bilgileri alınamadı! (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Git ve Besteci kurulumları ile birlikte bu güncelleme modülünü kullanmayın!',
    'Downloading update package' => 'Güncelleme paketi indiriliyor',
    'Extracting package files' => 'Paket dosyaları çıkartılıyor',
    'Installing files' => 'Dosyaları yükleme',
    'Make sure all files are writable by application' => 'Tüm dosyalar ve uygulamalar yazılabilir olduğundan emin olun',
    'Make sure all files are writable! (' => 'Tüm dosyaların yazılabilir olduğundan emin olun! (',
    'Make sure custom modules or themes are compatible with version %version%' => 'Özel modüller ve tema sürümü ile uyumlu olduğundan emin olun',
    'Migrating database' => 'Veritabanı taşınıyor',
    'New updater version available!' => 'Yeni güncelleyici sürümü mevcut!',
    'No error message available. Please check logfiles!' => 'Hata mesajı yok. Lütfen günlük dosyalarını kontrol edin!',
    'Please note:' => 'Lütfen aklınızda bulundurun:',
    'Please update installed marketplace modules before and after the update' => 'Güncellemeden önce ve sonra yüklü olan modülleri güncelleyin',
    'Preparing system' => 'Sistem hazırlığı',
    'Start' => 'Başla',
    'Start update' => 'Güncellemeyi Başlat',
    'The update was successfully installed!' => 'Güncelleme başarıyla yüklendi!',
    'There is a new update to %version% available!' => 'Yeni bir sürüm %version% mevcut!',
    'There is a new version of the updater module available. Please update before proceed.' => 'Güncelleyici modülünün yeni bir sürümü mevcut. Lütfen devam etmeden önce güncelleyin.',
    'There is no new HumHub update available!' => 'Yeni güncelleme mevcut değil!',
    'Update HumHub' => 'HumHub Güncelle',
    'Update package invalid!' => 'Güncelleştirme paketi geçersiz!',
    'Update successful' => 'Güncelleme başarılı',
    'Validating package' => 'Paketi onayla',
];
