<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Close' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installing files' => '',
    'Make sure all files are writable! (' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update' => '',
    'The update was successfully installed!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'Update HumHub' => '',
    'Update successful' => '',
    'Validating package' => '',
    '<strong>Update</strong> HumHub' => 'HumHub <strong>Güncelleme</strong>',
    'Backup all your files & database before proceed' => 'Tüm dosyalarınızı ve veritabanını yedekleyin',
    'Could not extract update package!' => 'Güncelleştirme paketi açılamadı!',
    'Could not get update info online! (%error%)' => 'Aktif güncelleme bilgileri alınamadı! (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Git ve Besteci kurulumları ile birlikte bu güncelleme modülünü kullanmayın!',
    'Make sure all files are writable by application' => 'Tüm dosyalar ve uygulamalar yazılabilir olduğundan emin olun',
    'Make sure custom modules or themes are compatible with version %version%' => 'Özel modüller ve tema sürümü ile uyumlu olduğundan emin olun',
    'Please note:' => 'Lütfen aklınızda bulundurun:',
    'Please update installed marketplace modules before and after the update' => 'Güncellemeden önce ve sonra yüklü olan modülleri güncelleyin',
    'There is a new update to %version% available!' => 'Yeni bir sürüm %version% mevcut!',
    'There is no new HumHub update available!' => 'Yeni güncelleme mevcut değil!',
    'Update package invalid!' => 'Güncelleştirme paketi geçersiz!',
];
