<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Close' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installing files' => '',
    'Make sure all files are writable! (' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update' => '',
    'The update was successfully installed!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'Update HumHub' => '',
    'Update successful' => '',
    'Validating package' => '',
    '<strong>Update</strong> HumHub' => '<strong>Mettre à jour</strong> HumHub',
    'Backup all your files & database before proceed' => 'Sauvegarder tous vos fichiers et votre base de données avant de continuer',
    'Could not extract update package!' => 'Impossible d\'extraire le paquet de mise à jour !',
    'Could not get update info online! (%error%)' => 'Impossible d\'obtenir des informations de mise à jour  (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Ne pas utiliser cet outil de mise à jour avec des installations réalisées avec Git ou Composer !',
    'Make sure all files are writable by application' => 'Assurez-vous que tous les fichiers sont inscriptibles par l\'application',
    'Make sure custom modules or themes are compatible with version %version%' => 'Assurez-vous que vos modules sur mesure ou thèmes sont compatibles avec la version %version%',
    'Please note:' => 'Merci de noter :',
    'Please update installed marketplace modules before and after the update' => 'Merci de mettre à jour les modules installés depuis la marketplace avant et après la mise à jour',
    'There is a new update to %version% available!' => 'Il y a une nouvelle mise à jour vers la version %version% disponible !',
    'There is no new HumHub update available!' => 'Il n\'y a pas de mise à jour de HumHub disponible !',
    'Update package invalid!' => 'Paquet de mise à jour invalide !',
];
