<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application folder not writable!' => '',
    'Application folder: {folder}' => '',
    'Installed PHP version not support!' => '',
    'Please update installed modules when new version is available!' => '',
    'Switch to default theme after update (strongly recommended)' => '',
    'The currently installed PHP version is too old. Please update before proceed.' => '',
    'The updater requires write access to <strong>all</strong> files and folders in the application root folder.' => '',
    '<strong>Update</strong> HumHub' => '<strong>Atualizar</strong> HumHub',
    '<strong>Update</strong> to HumHub {version}' => '<strong>Atualizar</strong> para HumHub {version}',
    'Abort' => 'Abortar',
    'Backup all your files & database before proceed' => 'Faça o backup de todos os seus arquivos e banco de dados antes de prosseguir',
    'Changes to HumHub core files may overwritten during update!' => 'Alterações nos arquivos do núcleo do HumHub podem ser substituídas durante a atualização!',
    'Cleanup update files' => 'Limpar arquivos de atualização',
    'Close' => 'Fechar',
    'Could not extract update package!' => 'Não foi possível extrair o pacote de atualização!',
    'Could not get update info online! (%error%)' => 'Não foi possível verificar informações de atualização online! (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Não utilize este atualizador em combinação com as instalações do Git ou do Composer!',
    'Downloading update package' => 'Fazendo download do pacote de atualização',
    'Extracting package files' => 'Extraindo arquivos de pacote',
    'Installing files' => 'Instalando arquivos',
    'Make sure all files are writable by application' => 'Verifique se todos os arquivos são graváveis pelo aplicativo',
    'Make sure all files are writable! (' => 'Certifique-se de que todos os arquivos são graváveis! (',
    'Make sure custom modules or themes are compatible with version %version%' => 'Verifique se os módulos ou temas personalizados são compatíveis com a versão %version%',
    'Migrating database' => 'Migrando banco de dados',
    'New updater version available!' => 'Nova versão do atualizador disponível!',
    'No error message available. Please check logfiles!' => 'Nenhuma mensagem de erro disponível. Verifique os arquivos de log!',
    'Please note:' => 'Por favor note que:',
    'Please update installed marketplace modules before and after the update' => 'Atualize os módulos de mercado instalados antes e depois da atualização',
    'Preparing system' => 'Preparando sistema',
    'Start' => 'Iniciar',
    'Start update' => 'Iniciar atualização',
    'The update was successfully installed!' => 'A atualização foi instalada com sucesso!',
    'There is a new update to %version% available!' => 'Há uma nova atualização disponível para %version%!',
    'There is a new version of the updater module available. Please update before proceed.' => 'Existe uma nova versão do módulo de atualização disponível. Atualize antes de prosseguir.',
    'There is no new HumHub update available!' => 'Não há nenhuma atualização HumHub disponível!',
    'Update HumHub' => 'Atualizar Humhub',
    'Update package invalid!' => 'Pacote de atualização inválido!',
    'Update successful' => 'Atualização bem sucedida',
    'Validating package' => 'Validando pacote',
];
