<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> HumHub' => '',
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Application folder not writable!' => '',
    'Application folder: {folder}' => '',
    'Backup all your files & database before proceed' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Could not extract update package!' => '',
    'Could not get update info online! (%error%)' => '',
    'Do not use this updater in combination with Git or Composer installations!' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installed PHP version not support!' => '',
    'Installing files' => '',
    'Make sure all files are writable by application' => '',
    'Make sure all files are writable! (' => '',
    'Make sure custom modules or themes are compatible with version %version%' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Please note:' => '',
    'Please update installed marketplace modules before and after the update' => '',
    'Please update installed modules when new version is available!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update (strongly recommended)' => '',
    'The currently installed PHP version is too old. Please update before proceed.' => '',
    'The update was successfully installed!' => '',
    'The updater requires write access to <strong>all</strong> files and folders in the application root folder.' => '',
    'There is a new update to %version% available!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'There is no new HumHub update available!' => '',
    'Update HumHub' => '',
    'Update package invalid!' => '',
    'Update successful' => '',
    'Validating package' => '',
    'Close' => 'Fechar',
];
