<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Close' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installing files' => '',
    'Make sure all files are writable! (' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update' => '',
    'The update was successfully installed!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'Update HumHub' => '',
    'Update successful' => '',
    'Validating package' => '',
    '<strong>Update</strong> HumHub' => '<strong>Update</strong>',
    'Backup all your files & database before proceed' => 'Maak een backup van je bestanden en database voordat je verder gaat!',
    'Could not extract update package!' => 'Kon het update pakket niet uitpakken!',
    'Could not get update info online! (%error%)' => 'Kon geen update informatie ophalen! (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Gebruik deze updater niet in combinatie met Fit of Composer installaties!',
    'Make sure all files are writable by application' => 'Zorg ervoor dat alle bestanden schrijfbaar zijn door de applicatie.',
    'Make sure custom modules or themes are compatible with version %version%' => 'Zorg er voor dat je modules en thema\'s compatibel zijn met versie %version%',
    'Please note:' => 'Let op:',
    'Please update installed marketplace modules before and after the update' => 'Update je modules voor EN na de update',
    'There is a new update to %version% available!' => 'Er is een nieuwe update naar versie %version% beschikbaar!',
    'There is no new HumHub update available!' => 'Er is geen nieuwe update beschikbaar.',
    'Update package invalid!' => 'Update pakket ongeldig!',
];
