<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Close' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installing files' => '',
    'Make sure all files are writable! (' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update' => '',
    'The update was successfully installed!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'Update HumHub' => '',
    'Update successful' => '',
    'Validating package' => '',
    '<strong>Update</strong> HumHub' => '<strong>HumHub</strong> aktualisieren',
    'Backup all your files & database before proceed' => 'Vor dem Fortfahren eine Sicherheitskopie aller Dateien und der Datenbank erstellen',
    'Could not extract update package!' => 'Konnte das Updatepaket nicht entpacken!',
    'Could not get update info online! (%error%)' => 'Konnte keine Updateinformationen beziehen! (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Diese Modul nicht in Kombination mit Git- oder Composer-Installationen benutzen!',
    'Make sure all files are writable by application' => 'Stelle sicher, dass alle Dateien durch die Anwendung überschrieben werden können',
    'Make sure custom modules or themes are compatible with version %version%' => 'Stelle sicher, dass individuelle Module und Themes mit der Version %version% kompatibel sind',
    'Please note:' => 'Bitte beachten:',
    'Please update installed marketplace modules before and after the update' => 'Bitte installierte Module vor und nach dem Update aktualisieren',
    'There is a new update to %version% available!' => 'Ein Update auf %version% ist verfügbar!',
    'There is no new HumHub update available!' => 'Es kein HumHub-Update verfügbar!',
    'Update package invalid!' => 'Updatepaket ungültig!',
];
