<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> to HumHub {version}' => '',
    'Abort' => '',
    'Changes to HumHub core files may overwritten during update!' => '',
    'Cleanup update files' => '',
    'Close' => '',
    'Downloading update package' => '',
    'Extracting package files' => '',
    'Installing files' => '',
    'Make sure all files are writable! (' => '',
    'Migrating database' => '',
    'New updater version available!' => '',
    'No error message available. Please check logfiles!' => '',
    'Preparing system' => '',
    'Start' => '',
    'Start update' => '',
    'Switch to default theme after update' => '',
    'The update was successfully installed!' => '',
    'There is a new version of the updater module available. Please update before proceed.' => '',
    'Update HumHub' => '',
    'Update successful' => '',
    'Validating package' => '',
    '<strong>Update</strong> HumHub' => '<strong>بروز رساني مهيا</strong>',
    'Backup all your files & database before proceed' => 'از تمامي فايل ها و ديتابيس خود بكاپ كامل بگيريد',
    'Could not extract update package!' => 'فايل بروزرساني نصب نشد',
    'Could not get update info online! (%error%)' => 'بروزرساني آنلاين انجام نشد.....كد ارور (%error%)',
    'Do not use this updater in combination with Git or Composer installations!' => 'Do not use this updater in combination with Git or Composer installations!',
    'Make sure all files are writable by application' => 'مطمئن شويد تمامي فايل ها قابل نوشتن هستند',
    'Make sure custom modules or themes are compatible with version %version%' => 'مطمئن شويد قالب و تمامي ماژول ها با نسخه جديد سازگارند ....  نسخه %version%',
    'Please note:' => 'يادداشت كنيد :',
    'Please update installed marketplace modules before and after the update' => 'Please update installed marketplace modules before and after the update',
    'There is a new update to %version% available!' => 'آپديت جديدي در دسترس است....نسخه (%version%)',
    'There is no new HumHub update available!' => 'آپديت جديدي براي مهيا موجود نيست',
    'Update package invalid!' => 'مجموعه نصب غير معقول',
];
