<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Update</strong> HumHub' => '',
    '<strong>Update</strong> HumHub <sup>BETA</sup>' => '',
    'Backup all your files & database before proceed' => '',
    'Check for next update' => '',
    'Could not extract update package!' => '',
    'Could not get update info online! (%error%)' => '',
    'Database migration results:' => '',
    'Do not use this updater in combination with Git or Composer installations!' => '',
    'Downloading update package...' => '',
    'Error!' => '',
    'Installing update package...' => '',
    'Make sure all files are writable by application' => '',
    'Make sure custom modules or themes are compatible with version %version%' => '',
    'Please make sure following files are writable by application:' => '',
    'Please note:' => '',
    'Please update installed marketplace modules before and after the update' => '',
    'Proceed Installation' => '',
    'Release Notes:' => '',
    'Show database migration results' => '',
    'Start Installation' => '',
    'The following files seems to be not original (%version%) and will be overwritten or deleted during update process.' => '',
    'There is a new update to %version% available!' => '',
    'There is no new HumHub update available!' => '',
    'Update HumHub <sup>BETA</sup>' => '',
    'Update package invalid!' => '',
    'Warning!' => '',
    'Warnings:' => '',
    'successfully installed!' => '',
    'version update' => '',
];
